### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by amueller** [automl/TabPFN#10]
Hey folks!
This is amazing work!

There's currently no license in this repo. Is that on purpose? If there's a chance to use Apache, that would be great!

**Comment by noahho** [comment]
Thanks for raising that issue Andreas! We briefly discussed this and went with the Apache license you suggested.

**Comment by tabpfn-anonym** [comment]
Sorry, we actually haven't acted on this yet, but will do so soon!

**Comment by noahho** [comment]
Sorry, we actually haven't acted on this yet, but will do so soon.

**Comment by SamuelGabriel** [comment]
We had a discussion on this and Noah, now re-enacted the Apache 2 certificate. :)
