### ISSUE TITLE
Problems saving a trained model

### ISSUE THREAD

**Issue by davidfrankenberg** [automl/TabPFN#11]
Hi, I have been playing with your model with frankly some impressive results. But I struggle when trying to save a trained model. I tried to use pickle but I got an error. It seems that there is a component that is not serializable. 

Is there other way to save a trained model?

Thanks.

By the way, this is the exception I get:

`AttributeError: Can't pickle local object 'load_model.<locals>.<lambda>'`

**Comment by noahho** [comment]
Hi David,

There's a pull request by @Thytu that solves that exact issue: https://github.com/automl/TabPFN/pull/9 
We couldn't integrate into the main branch yet, but maybe you can use Thytus suggestion.

Best
Noah

**Comment by davidfrankenberg** [comment]
Thanks!
