### ISSUE TITLE
Data Pre-Checks

### ISSUE THREAD

**Issue by simonprovost** [automl/TabPFN#2]
Dear authors,

Once again, great contribution to the AutoML area ✅

**Brief of the issue**

Surprisingly, the following code snippet reveals that the Sklearn check array method is present in your code to verify whether or not the training X matrix/array is correct. Nonetheless, it is commented (i.e, not currently used). I foolishly followed the Readme even though I knew there would be errors, but nothing mentioned that my data had just NaN values and that it was not computable.

**Naive and quick proposal**

In the event of an error in the predict proba method, you should execute the check array that directs the user to the actual error. Nonetheless, I completely understand that checking the matrice X may be pointless if we consider that the data we feed the system is already compute-ready; yet, if there is an issue, which could be the case, I assume you should report this to the user of your system in the correct manner. Finally, this naive and quick proposal of reporting directly to the user only if there was a crash would not affect the computation time if the data is already suitable for computation, therefore benchmarks, etc. are unaffected (in theory).

_Current code snippet:_

```python
    def predict_proba(self, X, normalize_with_test=False):
        # Check is fit had been called
        check_is_fitted(self)

        # Input validation
        # X = check_array(X)
```

_Naive proposal as I do not have the time yet to try it due to research related duties:_

```python

        try:
            X_full = np.concatenate([self.X_, X], axis=0)
            X_full = torch.tensor(X_full, device=self.device).float().unsqueeze(1)
            y_full = np.concatenate([self.y_, np.zeros_like(X[:, 0])], axis=0)
            y_full = torch.tensor(y_full, device=self.device).float().unsqueeze(1)
    
            eval_pos = self.X_.shape[0]
    
            prediction = transformer_predict(self.model[2], X_full, y_full, eval_pos,
                                             device=self.device,
                                             style=self.style,
                                             inference_mode=True,
                                             preprocess_transform='none' if self.no_preprocess_mode else 'mix',
                                             normalize_with_test=normalize_with_test,
                                             N_ensemble_configurations=self.N_ensemble_configurations,
                                             softmax_temperature=self.temperature,
                                             combine_preprocessing=self.combine_preprocessing,
                                             multiclass_decoder=self.multiclass_decoder,
                                             feature_shift_decoder=self.feature_shift_decoder,
                                             differentiable_hps_as_style=self.differentiable_hps_as_style
                                             , **get_params_from_config(self.c))
            prediction_, y_ = prediction.squeeze(0), y_full.squeeze(1).long()[eval_pos:]
    
            return prediction_.detach().cpu().numpy()
        
        except Exception as e:
           raise check_array(X)
```

I hope this assists! Noting that I knew there will be an error, I stupidly submitted my data without imputed it beforehand, which may appear to be a common occurrence for some users, the idea is to correctly reporting that to the users.

Cheers,

**Comment by noahho** [comment]
Hi Simon,

Thank you very much for your contribution, this helps indeed!

Similar to what you suggested, I enabled the function check_array(X). I did not use it within the try catch syntax but enabled checking by default - calling check_array is extremely fast so this won't change performance. In our case we want to allow for Nans as input, so i am using check_array(..., force_all_finite=False). This also still allows the case where all inputs are set to np.nan, but have correct shapes etc., as this is the standard sklearn error handling. 

Thanks a lot!
