### ISSUE TITLE
Feature importance

### ISSUE THREAD

**Issue by apderosa** [automl/TabPFN#20]
Hi, amazing job! I was testing your model on my data and I was wondering if there is any chance to get feature importance scores (similarly to other ML models). Is it possible to get them in some way from the model as it is or you plan to add the feature importance attribute in future?

Thank you!

**Comment by noahho** [comment]
Hi apderosa,

Sorry for the slow answer. I was hoping to send you working code for that already or have it integrated. Unfirtunately could'nt make it yet. 
I can share some snippets that might help. Here I am using the shap library for explainability and simply integrated TabPFN through the sklearn interface. 
`import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    # compute SHAP values
    background = shap.maskers.Independent(train_xs.numpy(), max_samples=1000)
    explainer = shap.explainers.Permutation(classifier.predict_proba, custom_masker)
    shap_values = explainer(X_xplain)
`

Hope this helps!
Best
Noah

**Comment by fif911** [comment]
Hi Noah

Was there any continuation of work on this? I found something like this but not sure how easily this can be integrated:
https://github.com/david-rundel/tabpfn_iml

Best regards, Oleksandr
