### ISSUE TITLE
Regression? 

### ISSUE THREAD

**Issue by GLambard** [automl/TabPFN#21]
Thank you very much for your work! 
Also, can you use TabPFN for regression tasks? And if not, do you intend to provide it with such a capability soon? 

Thank you!

**Comment by noahho** [comment]
Thanks for the Feedback! We are working on regression right now, but unfortunately can't give a good timeline for when evaluation is done. Stay tuned :)

**Comment by Borda** [comment]
> We are working on regression right now, but unfortunately can't give a good timeline for when evaluation is done. Stay tuned :)

could you pls eventually advise how we could help? :flamingo:
