### ISSUE TITLE
Difficulties with reproducing the training 

### ISSUE THREAD

**Issue by puhsu** [automl/TabPFN#24]
Hey 👋 

Thanks for the awesome project! I'm very excited with the universal tabular model idea and your results are quite impressive!

I was trying to reproduce the training, but got into some troubles. I guess that the `train.py` file is not the main entry-point into training the TabPFN transfomer, I found some configs in the `PriorFittingCustomPrior.ipynb` notebook along with the `get_model` function, which appears to train the model, but there are still some things I couldn't understand. 

Could you please provide some details about the config which was used to produce the checkpoint?

Could you also provide additional details on priors:
- What is prior_bag (I guess it sequentially samples or something?)?
- What is fast_gp prior and how it is used in the context of the tabular prior (there are no mentions of the Gaussian Processes in the TabPFN paper, only in the original PFN paper)?
- Am I understanding correctly that the `DifferentiableHyperparameter` code is used only to sample dataset parameters from ranges set in the configs (and described in table 5 of the appendix)?

**Comment by noahho** [comment]
Hi Ivan,

You are right the PriorFittingCustomPrior.ipynb notebook is used for training and the get_model function trains the model. The configs set in PriorFittingCustomPrior.ipynb reproduce our model. The configs are first retrieved from the function get_prior_config (scripts.model_configs) and then some settings are overwritten in the notebook.

- What is prior_bag (I guess it sequentially samples or something?)?
**It mixes different prior models, i.e. it randomly selects either one model or another. In the repo, the Gaussian process prior is mixed with the SCM and BNN prior. However, in the config the weight of the GP prior is set to 0 however so the prior_bag does not have a function in that case. **
- What is fast_gp prior and how it is used in the context of the tabular prior (there are no mentions of the Gaussian Processes in the TabPFN paper, only in the original PFN paper)?
**See above**
- Am I understanding correctly that the DifferentiableHyperparameter code is used only to sample dataset parameters from ranges set in the configs (and described in table 5 of the appendix)?
**Yes exactly. In the configs dict in key differentiable_hyperparameters, there are the keys of hyperparameters that are sampled alongside distributions from which they are sampled. The sampled hyperparameters overwrite the values in the config dictionary (i.e. outside the differentiable_hyperparameters key) after they are sampled.**

I hope this helps. We are also working to document things better overall, but unfortunately still need some time.
Best

**Comment by puhsu** [comment]
Yep! This helps! Didn't see the 0 probability for gp prior 😅  
Now everything makes sense! 

Thanks for the prompt response!
