### ISSUE TITLE
silly question: learning curves

### ISSUE THREAD

**Issue by amueller** [automl/TabPFN#27]
This is probably a stupid question, but I was wondering if/how you stored learning curves during training. I can't find anything in the code that records the losses. Maybe there's some built-in torch mechanism that I'm unaware of?

Obviously I can build a list myself and serialize that but I figure you must have done it some way as well...

**Comment by SamuelGabriel** [comment]
Actually, we never really had anything for this... 😅

I use this code on the `stdout`:

```
def get_all_losses(stdout):
    return [float(v) for v in re.findall('mean loss (.*) \|',stdout)]
```

but yeah it is horribly hacky.
