### ISSUE TITLE
collaboration

### ISSUE THREAD

**Issue by microprediction** [automl/TabPFN#3]
Hi. I maintain a site where people launch fully autonomous algorithms and they compete. I'm curious about the application of tabpfn to univariate time-series (probably post generation of a few features, or as a way of providing a meta-model). It seems that the single pass could be very fast an effective in this setting. LMK if you think unleashing your algo in this fashion is interesting, and we can probably meet halfway in the middle of our APIs. 
-Peter

**Comment by noahho** [comment]
Hi, great work on your site! Lots of requests at the moment, but didn't want to make you wait, sorry if this is a bit short. As of now TabPFN isn't really made for time series (even though features could be data from different time points). Is there something in particular you would need tio have changed? Could you use of sklearn interface which seems standard for classification tasks?

**Comment by microprediction** [comment]
Hi Noah, Samuel,
   No need to reopen this but just noticed your response. Yeah, I'll have a try on time-series classification (e.g. what model will work best in the near horizon) and get back to you. One thing I don't understand yet is what happens in "fit" exactly, but I'll trace in and educate myself. Keep it up. Pooh to the critics. 
Peter
