### ISSUE TITLE
cannot import name 'TabPFNClassifier' from 'tabpfn' (unknown location)

### ISSUE THREAD

**Issue by jzhang305** [automl/TabPFN#32]
Thanks for sharing. I met this problem when I trying to follow the instruction:

![image](https://user-images.githubusercontent.com/72380990/222343217-bf751fe8-26cd-4e68-b180-49642f867750.png)

**Comment by noahho** [comment]
It seems that something went wrong with your installation. Could you try installing tabpfn using: pip install tabpfn? Here is a demo, where you can see how to install tabpfn using pip: https://colab.research.google.com/drive/194mCs6SEPEW6C0rcP7xWzcEtt1RBc8jJ#scrollTo=N8mEqwDWHD5S 

Hope this helps already.
