### ISSUE TITLE
AttributeError: 'TabPFNClassifier' object has no attribute 'no_grad'

### ISSUE THREAD

**Issue by miquelduranfrigola** [automl/TabPFN#35]
Hi!

Thanks for a fantastic tool.

I fitted some models a while ago, and now when trying to deploy them on another computer I get this error in the predict_proba method:

```
AttributeError: 'TabPFNClassifier' object has no attribute 'no_grad'
```

May I know when was the self.no_grad attribute introduced? I would like to fall back to the old tabpfn version in this particular case

**Comment by noahho** [comment]
Hi Miguel,

Ohh I'm sorry we introduced that bug. If you go back to the last version that should be resolved. If you can actually load your old classifiers, you can also get the data for fitting and create a new classifer.
`
X_ = tabpfn.X_
y_ = tabpfn.y_
tabpfn = TabPFNClassifier()
tabpfn.fit(X_, y_)
`

Hope that helps
