### ISSUE TITLE
aggregate_k_gradients default defined twice in get_model

### ISSUE THREAD

**Issue by amueller** [automl/TabPFN#39]
If ``aggregate_k_gradients`` is not defined, it's assigned some magic default, but later, it's checked again and if not defined it is set to 1 (which can never happen because we just set it).

**Comment by SamuelGabriel** [comment]
True! Thanks for finding this. I updated it: https://github.com/automl/TabPFN/commit/a51f19f5670383a00224cbcbf7ed001abb48d687
