### ISSUE TITLE
Take forever to load pretrained checkpoint on Macbook M1

### ISSUE THREAD

**Issue by hqng** [automl/TabPFN#43]
Currently I am using python 3.9 on Macbook M1. When I initiate the TabPFN, it download the pretrained checkpoint but then take forever to load the model (even if with n_ensemble_config small). Is there anyone had the same issue and fix it? it doens't output anything so I am not sure where to fix it.

**Comment by noahho** [comment]
Loading the model is usally a fast step. Might there be a problem with the available memory on your device? Could you try loading TabPFN on CPU or CUDA and see if any of these two settings works?
```
classifier = TabPFNClassifier(device='cpu', N_ensemble_configurations=32)
classifier = TabPFNClassifier(device='cuda', N_ensemble_configurations=32)
```
This is the step which is slow for you?
Could you profile your RAM usage?
