### ISSUE TITLE
How to include TabPFN in TPOT's custom dictionary

### ISSUE THREAD

**Issue by apavlo89** [automl/TabPFN#46]
I try to include TABPFN to TPOT's custom dictionary like so:

    'tabpfn.TabPFNClassifier':{
        'device':['cpu'], 
        'N_ensemble_configurations': list(range(2, 39))
    },

But I just get warning:

Loading model that can be used for inference only
Using a Transformer with 25.82 M parameters

How can I fix this?

**Comment by noahho** [comment]
Not sure how this works for tpot, you might have to ask the people from tpot.

What I can tell you is that the message above is printed when you load the tabpfn model, it's not a warning.
