### ISSUE TITLE
SCM vs. BNN

### ISSUE THREAD

**Issue by NivC** [automl/TabPFN#51]
Thank you very much for this paper and sharing the code!

A small question please:
In the paper you show the results of the SCM prior and the BNN prior.
Which configurations in the code please would correspond to these results?
(e.g., I assume the 'mlp.py' prior gives the SCM, is this right? 
which hyper-parameters can I use please to replicate the SCM-only results? which file gives the BNN prior?).

Thanks once again!
Niv.

**Comment by setipsh** [comment]
I’m also curious about this. Do you know now? If you do, could you share it?
