### ISSUE TITLE
How to disable overwrite_warning=True without putting it in fit

### ISSUE THREAD

**Issue by apavlo89** [automl/TabPFN#52]
Is there a way to disable this warning as I want to use TabPFN as a stacking estimator (using TPOT's easy stacking estimator functionality). I've tried a bunch of ways but I think the only is to disable this bs from TabPFN script.. Any advice on how to do that?

**Comment by noahho** [comment]
```
from functools import partial
classifier = TabPFNClassifier(device=device, N_ensemble_configurations=16)
classifier.fit = partial(classifier.fit, overwrite_warning=True)
```
