### ISSUE TITLE
Hyperparameters for XGBoost models in Table 2

### ISSUE THREAD

**Issue by georgestein** [automl/TabPFN#54]
The HPO functionality is included in the codebase but I am unable to find the final hyperparameters used for each dataset in Table 2. 

These would be very valuable - specifically the XGBoost parameters.

Are you able to provide these?

**Comment by noahho** [comment]
Take a look here: https://github.com/automl/TabPFN/blob/main/tabpfn/scripts/tabular_baselines.py#L1292

**Comment by georgestein** [comment]
This is the HPO code I referenced that defines the large search space. 

What I am looking for the final parameters that were arrived at for each dataset, so that I can reproduce the models in Table 2. 

Are you able to provide those final parameters for the XGBoost models?

**Comment by noahho** [comment]
Ahh, my misunderstanding.

Those parameters might be in the files at https://github.com/ravinkohli/TabPFNRawResultsHourSearch/tree/master/results/tabular/multiclass which is loaded from https://colab.research.google.com/drive/1Rvf7oTvI09Urrdt-RVcCPMVIZys-X3wo#scrollTo=tHdshzwIh1c6 - I am not sure however.

In any case, the seeds are fixed so rerunning the hp search should yields very similar results (unless your cores run much faster or slower than ours).

**Comment by georgestein** [comment]
No worries! Okay great I will take a look there. Thank you for your help.
