### ISSUE TITLE
What are the input values for encoder and decoder?

### ISSUE THREAD

**Issue by Sakura5540** [automl/TabPFN#55]
Since the training process is not provided in the code, I would like to ask what are the inputs for encoder and decoder respectively?
Thank you

**Comment by noahho** [comment]
Not sure I understand your question.
The PriorFitting Phase can be reproduced here: https://github.com/automl/TabPFN/blob/main/tabpfn/PriorFittingCustomPrior.ipynb
You can train on your own datasets here: https://github.com/automl/TabPFN/blob/main/tabpfn/QuickPredictionDemo.ipynb

Hope this helps!
