### ISSUE TITLE
GPU Warning on breast cancer example from git

### ISSUE THREAD

**Issue by blazespinnaker** [automl/TabPFN#6]
When I run the code on the home page, https://github.com/automl/TabPFN,  I get this warning:

`/opt/conda/lib/python3.7/site-packages/torch/autocast_mode.py:162: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')`

This is even though cpu is being sent as the device in the classifier instantiation.  The fit/predict also seemed rather slow.

**Comment by noahho** [comment]
Thanks for pointing this out! You should not see the warning anymore when using the code from this repo, it does however not change performance.

There is a parameter called N_ensemble_configurations which was set to 32 by default. That means that we ran the model 32 times and average. While this increased accuracy a little, I changed the default to 3 now based on your/recent community feedback.

You can set this value yourself depending on your requirements.

Best

**Comment by blazespinnaker** [comment]
Very cool.  Nice results on the breast cancer dataset.  I tried another dataset on Kaggle, Titanic, a classic classifier problem.

Using default hyper parameters for every model:

![image](https://user-images.githubusercontent.com/2188809/197368037-ccaa06bc-241a-4b0e-bb4d-5c8e159fe7a2.png)

Still, I think the results and approach is very cool.  It's similar to the huggingface MLP model of fine tuning in a way.  Taking that approach to classifier / regression problems could be very fruitful.  The trick, I think, would be developing a compelling nomenclature for problem sets so folks could pick the right model for the right problem.   Of course, a one model to rule them all is cool, but maybe solve the easy problem first.

Love this diagram though!  Might be a good start for designing an approach to describing different datasets.

![image](https://user-images.githubusercontent.com/2188809/197368108-1ea18c52-55a2-4422-b8b5-59b115b18944.png)
