### ISSUE TITLE
TabPFNClassifier.predict raise torch warning

### ISSUE THREAD

**Issue by G-Piotr** [automl/TabPFN#60]
`classifier.predict` results in:
_Lib\site-packages\torch\utils\checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(_

where `classifier = TabPFNClassifier(device='cpu', N_ensemble_configurations=32)`
torch version '2.1.0+cpu' for current TabPFN

**Comment by noahho** [comment]
This shouldn't change behavior, but you can catch warning if you like to (https://stackoverflow.com/questions/5644836/in-python-how-does-one-catch-warnings-as-if-they-were-exceptions)
Correct torch version would be 1.9, thats why youre getting this warning, but as I said probably you don't need to worry.
