### ISSUE TITLE
It takes a long time to download checkpoint file.

### ISSUE THREAD

**Issue by TyrionWuYue** [automl/TabPFN#62]
Because of the company VPN or some other network reasons (I guess), it takes a long time to download checkpoint file when I run TabPFN = TabPFNClassifier(device = 'cpu', N_ensemble_configurations = 32) in Jupyter Notebook. And I found there is a file called 'prior_diff_real_checkpoint_n_0_epoch_42.cpkt', when I download it manually and rename it, the code could works well. But I think 'prior_diff_real_checkpoint_n_0_epoch_100.cpkt' should be more powerful, could you provide some methods to bypass downloading when running the code? Or update the checkpoint file in github?

**Comment by lionbiubiubiu** [comment]
I also discovered this issue. Although the local file already contains "models_diff/primaor_diff_real_checkpoint_20_epoch_42. cpkt",

However, when running TabPFN=TabPFNClassifier (device='cpu ', N_ensemble configurations=32), the code actually first checks that there is no local file named "prior_diff_real_checkpoint_10_epoch_100. cpkt"

**Comment by lionbiubiubiu** [comment]
I've come across a similar issue. Even though the "models_diff/prior_diff_real_checkpoint_n_0_epoch_42.cpkt" file is already in place on my machine, when I execute TabPFN = TabPFNClassifier(device = 'cpu', N_ensemble_configurations = 32), the script seems to be looking for a non-existent file named "prior_diff_real_checkpoint_n_0_epoch_100.cpkt" first.

**Comment by SamuelGabriel** [comment]
yeah, that was a bug. Fangway fixed it though: https://github.com/automl/TabPFN/commit/5805a9a1481c10502909b0b142f978c580ca810f
