### ISSUE TITLE
Can you give an index list of the 18 datasets used for Table 1? 

### ISSUE THREAD

**Issue by yxzwang** [automl/TabPFN#65]
Hello, I'm running your code and I'm curious what are the 18 numerical datasets in OpenML-CC18 you used for Table 1 in your paper. The 'cc_test_datasets_multiclass' used in RunFullDatasetAnalyses.ipynb contains all 30 datasets. Can you provide an index list of the 18 ones for Table 1? Thank you.

**Comment by noahho** [comment]
I think you can run this code: https://github.com/automl/TabPFN/blob/main/tabpfn/RunFullDatasetAnalyses.ipynb (Section Datasets)
