### ISSUE TITLE
What should I do to reproduce your results?

### ISSUE THREAD

**Issue by herdonyan** [automl/TabPFN#66]
I use conda create to create a env with python=3.7. And I type 'pip install tabpfn[full]'. What should I do next to reproduce your training and experiments in your paper?

**Comment by noahho** [comment]
https://github.com/automl/TabPFN/blob/main/tabpfn/RunFullDatasetAnalyses.ipynb

**Comment by herdonyan** [comment]
Thanks for the notice. I want to train a model from start. Because I want to understand the function of SCM prior compared with no prior and BNN prior. Should I run the SCM prior fitting (such as PriorFittingCustomPrior.ipynb and PrepareDatasets.ipynb) before I run this file?
