### ISSUE TITLE
The transformer_prediction_interface.py needs to be modified.

### ISSUE THREAD

**Issue by oshanpo** [automl/TabPFN#7]
In order to be able to properly process data frames containing one-hot encoded features, line 187 of transformer_prediction_interface.py needs to be modified as follows
y_full = np.concatenate([self.y_, np.zeros_like(X.iloc[:, 0])], axis=0)

**Comment by noahho** [comment]
Could you please describe what your Problem is and what you are trying to solve? I have trouble following.

We do not one-hot encode features or targets, but leave class as integers.
