### ISSUE TITLE
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by CQQXY161120** [automl/TabPFN#72]
When I run the demo, I get the following error:ConnectionError: 
We have to download the TabPFN, as there is no checkpoint at  G:\anaconda\Lib\site-packages\tabpfn\models_diff/prior_diff_real_checkpoint_n_0_epoch_100.cpkt
It has about 100MB, so this might take a moment.

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by SamuelGabriel** [comment]
does this issue persist?
