### ISSUE TITLE
The variable "single_eval_position" has a chance of being zero.

### ISSUE THREAD

**Issue by liuquangao** [automl/TabPFN#83]
single_eval_pos_gen=get_uniform_single_eval_pos_sampler(config.get('max_eval_pos', config['bptt']), min_len=config.get('min_eval_pos', 100))

**Comment by SamuelGabriel** [comment]
Yeah, then the training set is simply empty. That is fine for our model, even though it sounds a little strange.

**Comment by liuquangao** [comment]
Thank you for your patience.
