### ISSUE TITLE
EnsembleTabPFN for bigger than 1000 rows dataset

### ISSUE THREAD

**Issue by ericleonardo** [automl/TabPFN#87]
Please, check the EnsembleTabPFN if you want to use TabPFN with bigger dataset:
[https://github.com/ersilia-os/chempfn](https://github.com/ersilia-os/chempfn)

There is no 1000 rows or 100 features limitation like original TabPFN.
The authors could build a new version for dealing with Imbalanced class dataset also.

Thank you!

**Comment by SamuelGabriel** [comment]
Hey, this looks great. This codebase neither has the limits strictly enforced anymore either. You can set config flags to overwrite both, features are subsampled in that case.

We are revamping this project a lot in a few months, though, and will update with a new version which deals with this, too.
