### ISSUE TITLE
Figure 5 paper

### ISSUE THREAD

**Issue by annawiewer** [automl/TabPFN#92]
Hello,

I was wondering if you could kindly provide more information about the plots included in your paper? Specifically, I’m interested in how Figure 5 was created.

Thank you!

<img width="751" alt="image" src="https://github.com/user-attachments/assets/455f99b3-2d0c-4047-95eb-983f7ddcc12f">

**Comment by noahho** [comment]
Dear Anna,

here is the notebook we ran for our plots: https://github.com/automl/TabPFN/blob/main/tabpfn/RunFullDatasetAnalyses.ipynb

Best!
