### ISSUE TITLE
18 numerical datasets mentioned in paper

### ISSUE THREAD

**Issue by fengyuli-dev** [automl/TabPFN#94]
Hello, is there a list of indices of the 18 purely numerical datasets among all 30 openml datasets?

I noticed there was a previous issue on this #65, however I tried to run the notebook mentioned in that issue but failed. Could the authors give a clearer guidance? Thanks!

**Comment by noahho** [comment]
Dear Fengyu

I am not sure about the script right now but would show how to find them based on the paper.

I have attached a screenshot of Table 7 in the Appendix, listing the evaluation datasets. How to get to the 18 datasets from that table:
- Only take datasets with "#Cat" (The number of categorical columns including the categorical target) is 1 and there are no "#NaN" entries (=0)
- The rightmost column shows the OpenML Id

<img width="944" alt="image" src="https://github.com/user-attachments/assets/2e1e478f-0601-4d18-8ddd-bc91433969df">

Best!
